# Generated by Django 4.0.3 on 2022-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElecSales', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
